Add missing docs
kartoza/SAEOSS-Portal pull request #302
Opened 2024-01-29 09:21 UTC by ketankartoza

This PR is for issue #299

2024-01-30 06:23 UTC, Jeremy-Prior requested changes

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/guide/forgot_password.md
The content is good but please look at some of the other guide docs to see the preferred formatting. This should be different to the manual.

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/guide/logout.md
> +**Logout Page**
```suggestion
## Logout Page
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/guide/logout.md
The content is good but please look at some of the other guide docs to see the preferred formatting. This should be different to the manual.

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/index.md
> +* **[SignUp:](./signup.md)** This is the `SignUp` page where the user can create an account.
```suggestion
* **[Sign Up:](./signup.md)** This is the `Sign Up` page where the user can create an account.
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/login.md
> +**Login Buttons:**
```suggestion
### Login Buttons
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/login.md
> +**Access Login Page:**
```suggestion
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/login.md
> +1. **Login Button:** Click on the login button available in the middle of the home page. Alternatively, locate and click on the login button in the top right corner of the page.
We should probably separate the second login button. e.g.
```suggestion
1. **Login Button:** Click on the login button available in the middle of the home page.
2. **Other Login Button:** Alternatively, locate and click on the login button in the top right corner of the page.
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/logout.md
> +The Logout option ensures a secure end to the user's session, redirecting the user to a dedicated logout page. From there, the user can conveniently navigate to different sections, including the home
```suggestion
The Logout option ensures a secure end to the user's session, redirecting the user to a dedicated logout page. From there, the user can conveniently navigate to different sections, including the home page, login page, and sign up page, using the provided buttons. Feel free to explore the various features available after logging out and return to the system at your convenience. If you have any further questions or need assistance, please reach out to our support team.
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +# Signup Page User Manual
```suggestion
# Sign Up Page User Manual
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +The `Signup` page allows users to create a new account, providing access to personalised features and content on the platform. This guide will walk users through the steps to sign up, including filli
```suggestion
The `Sign Up` page allows users to create a new account, providing access to personalised features and content on the platform. This guide will walk users through the steps to sign up, including filling out the required fields and creating their account.
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +1. **Access Signup Page:** Click on the signup button available in the middle of the home page. Alternatively, locate and click on the login button in the top right corner of the page, where the user
```suggestion
1. **Access Sign Up Page:** Click on the `SIGN UP` button available in the middle of the home page. 
2. **Other Access to Sign Up Page:** Alternatively, locate and click on the `SIGN UP` button in the top right corner of the page, where the user can find an option to create an account.
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +Creating a new account is a simple and essential step to unlock personalised features on our platform. Follow these steps to complete the signup process, and the user be ready to explore and engage w
```suggestion
Creating a new account is a simple and essential step to unlock personalised features on our platform. Follow these steps to complete the sign up process, and the user be ready to explore and engage with our community. If the user encounters any issues or has questions, feel free to contact the support team for assistance.
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +1. **Fill Out Signup Form:**
```suggestion
1. **Fill Out Sign up Form:**
```

2024-01-30 06:23 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +    The signup form includes the following fields:
```suggestion
    The sign up form includes the following fields:
```

2024-01-30 06:35 UTC, ketankartoza commented on docs/src/user/guide/forgot_password.md
okay

2024-01-30 16:12 UTC, ketankartoza commented on docs/src/user/guide/logout.md
okay

2024-01-31 07:09 UTC, Jeremy-Prior requested changes
Minor changes

@Jeremy-Prior Done!!

2024-01-31 07:09 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +## Signup Page
```suggestion
## Sign Up Page
```

2024-01-31 07:09 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +![signup page](./img/signup-2.png)
```suggestion
![sign up page](./img/signup-2.png)
```

2024-01-31 07:09 UTC, Jeremy-Prior commented on docs/src/user/manual/signup.md
> +![signup](./img/signup-1.png)
```suggestion
![sign up](./img/signup-1.png)
```

2024-01-31 07:13 UTC, Jeremy-Prior approved these changes
LGTM

2024-01-31 07:13 UTC, merged